#!/usr/bin/env python3
from pathlib import Path
import sys, hashlib
ROOT=Path(__file__).resolve().parents[2]; JS=ROOT/'js'
TEXT_EXT={'.html','.htm','.js','.mjs','.cjs','.json','.md','.yml','.yaml','.txt','.css','.webmanifest','.xml','.py'}
SKIP_DIRS={'.git','node_modules','vendor','.github'}
RULES=[('grain-','grain/shared'),('dash-','dashboard/shared'),('field-readiness-','field-readiness'),('boundary-','fields/boundaries'),('equipment-','equipment/shared'),('shop-','equipment/shop'),('trials-','calculators/trials'),('ai-reports','reports'),('markets','shared/markets'),('mb-','shared/message-board'),('menu-','shared/navigation'),('perm-','shared/permissions'),('copilot-','shared/ai'),('firebase-','core/firebase'),('fv-shell','core/shell'),('theme-','core/theme'),('version','core/version'),('core','core'),('fv-auto-update','core/updates'),('fv-map','shared/maps'),('fv-weather','shared/weather'),('fv-pdf','shared/export'),('fv-yield-','shared/calculators'),('fv-data','shared/data'),('fv-dictation','shared/input'),('fv-perms','shared/permissions'),('fv-','shared/ui')]
def digest(p): return hashlib.sha256(p.read_bytes()).hexdigest()
def classify(name):
    stem=name[:-3] if name.endswith('.js') else name
    for prefix,dest in RULES:
        if stem==prefix or stem.startswith(prefix): return JS/dest/name
    return JS/'shared'/name
root_js=sorted(p for p in JS.glob('*.js') if p.is_file()); nested={}
for p in JS.rglob('*.js'):
    if p.parent!=JS: nested.setdefault(p.name,[]).append(p)
mapping={}
for old in root_js:
    preferred=classify(old.name); matches=nested.get(old.name,[])
    if preferred in matches: new=preferred
    elif len(matches)==1: new=matches[0]
    else:
        exact=[p for p in matches if digest(p)==digest(old)]; new=exact[0] if len(exact)==1 else preferred
    new.parent.mkdir(parents=True,exist_ok=True); new.write_bytes(old.read_bytes()); mapping[old]=new
repls=[]
for old,new in mapping.items():
    o=old.relative_to(ROOT).as_posix(); n=new.relative_to(ROOT).as_posix(); repls += [('/'+o,'/'+n),(o,n)]
repls=sorted(set(repls),key=lambda x:len(x[0]),reverse=True); changed=[]
def eligible(p): return p.is_file() and not any(x in SKIP_DIRS for x in p.parts) and p.suffix.lower() in TEXT_EXT
for p in ROOT.rglob('*'):
    if not eligible(p): continue
    try: s=p.read_text(encoding='utf-8')
    except UnicodeDecodeError: continue
    t=s
    for a,b in repls: t=t.replace(a,b)
    if t!=s: p.write_text(t,encoding='utf-8'); changed.append(p)
for old in mapping: old.unlink()
for keep in JS.rglob('.gitkeep'):
    if any(x.is_file() and x.name!='.gitkeep' for x in keep.parent.iterdir()): keep.unlink()
stale=[]
for old in mapping:
    needles=['/'+old.relative_to(ROOT).as_posix(),old.relative_to(ROOT).as_posix()]
    for p in ROOT.rglob('*'):
        if not eligible(p): continue
        try: s=p.read_text(encoding='utf-8')
        except UnicodeDecodeError: continue
        for needle in needles:
            if needle in s: stale.append(f'{p.relative_to(ROOT)} -> {needle}')
remaining=list(JS.glob('*.js'))
if remaining or stale:
    print('Remaining root JS:',*[str(x.relative_to(ROOT)) for x in remaining],sep='\n'); print('Stale refs:',*stale,sep='\n'); sys.exit(3)
manifest=JS/'FINAL-MOVE-MANIFEST.md'; lines=['# Final JavaScript Move Manifest','','Generated by the deterministic restructure finisher.','']
for old,new in sorted(mapping.items(),key=lambda kv:kv[0].name): lines.append(f'- `{old.relative_to(ROOT).as_posix()}` → `{new.relative_to(ROOT).as_posix()}`')
manifest.write_text('\n'.join(lines)+'\n',encoding='utf-8')
(JS/'RESTRUCTURE-STATUS.md').write_text('# Major JavaScript Restructure — Status\n\n**COMPLETE — ready for folder-layout review.**\n\nWorking branch: `major-js-restructure-cleanup`\n\n- Root JavaScript files relocated into feature/subfeature folders.\n- Runtime repository consumers migrated to new paths.\n- Old root JavaScript duplicates removed after reference migration.\n- Root runtime files were treated as canonical, preserving behavior.\n- `fields/` and `field-readiness/` remain independent feature areas.\n- Runtime testing is the next phase after layout approval.\n- `main` was not modified by this restructure.\n',encoding='utf-8')
print(f'OK: moved {len(mapping)} root JS files; updated {len(changed)} runtime text files; audit clean.')
