import assert from 'node:assert/strict';
import {ticketSummary,ticketStatus,scanMillis,ticketAttentionReasons} from '../js/dashboard/kpi/grain-ticket-summary.js';
const job={id:'job',status:'active'};
const good={id:'good',createdAt:{seconds:Date.parse('2026-09-23T02:00:00Z')/1000},ticketDate:'2026-09-20',haulingJobId:'job',customerId:'customer',deliveryLocationId:'elevator',crop:'Corn',grainSourceType:'field',damage:0,foreignMaterial:0};
assert.equal(ticketStatus(good,[job]),'good');
assert.equal(ticketStatus({...good,validationStatus:'needs_review'},[job]),'good','Resolved assignment clears stale review flag');
assert.equal(ticketStatus({...good,damage:''},[job]),'review','Blank grade needs verification; zero is valid');
assert.equal(ticketStatus({...good,grossWeight:96000},[job]),'review');
assert.equal(ticketStatus({...good,haulingJobId:null},[job]),'needs_job');
assert.equal(ticketStatus({...good,haulingJobId:null,validationStatus:'needs_review',reviewReasons:['buyer_not_matched']},[job]),'warning');
assert.equal(ticketStatus({...good,haulingJobId:null,spotLoad:true},[job]),'good');
const nextDay={...good,id:'next',createdAt:'2026-09-23T05:00:00Z'};
const oldReview={...good,id:'old',createdAt:'2026-08-01T12:00:00Z',damage:30};
const summary=ticketSummary([good,nextDay,oldReview,{...good,id:'void',voided:true}], [job],'2026-09-22');
assert.deepEqual(summary.today.map(t=>t.id),['good'],'Scan date and Central midnight, not printed ticket date');
assert.deepEqual(summary.attention.map(t=>t.id),['old'],'Includes old unresolved tickets; excludes voids');
assert.equal(scanMillis({ticketDate:'2026-09-22'}),0,'No invented scan time from printed date');
assert.deepEqual(ticketSummary([],[], '2026-09-22'),{today:[],attention:[]});
console.log('PASS: grain KPI counts, Central scan date, review rules, assignment, spot loads, voids, and empty data');

assert.deepEqual(ticketAttentionReasons({...good,validationStatus:'needs_review',reviewReasons:['buyer_not_matched']},[job]),[],'Resolved assignments suppress stale reasons');
assert.deepEqual(ticketAttentionReasons({...good,damage:''},[job]),['Damage is missing or unreadable']);
assert.ok(ticketAttentionReasons({...good,haulingJobId:null,validationStatus:'needs_review',reviewReasons:['sold_under_unknown']},[job]).includes('Sold Under is unknown'));
assert.ok(ticketAttentionReasons({...good,ticketDate:'2999-01-01'},[job])[0].includes('future'));
console.log('PASS: attention reasons, missing grades, stale reasons, future dates');
