import assert from 'node:assert/strict';
import {buildAutomaticHaulingAssignment,buildHaulingReconciliation} from '../js/grain/operations/hauling/hauling-allocation.js';
import {effectiveJobTotals,ticketJobBushels,ticketSpotBushels,compatibleHaulingJob} from '../js/grain/operations/core/grain-rules.js';
import {runGrainScenarios} from '../js/grain/operations/core/grain-scenarios.js';
const identity={buyerId:'scoular',deliveryLocationId:'waverly',customerId:'dowson',crop:'Corn'};
const old={...identity,id:'old',startingBushels:5000,deliveryStartDate:'2026-09-01',deliveryEndDate:'2026-09-30',active:false,status:'completed'};
const next={...identity,id:'next',startingBushels:2500,deliveryStartDate:'2026-09-13',deliveryEndDate:'2026-09-30',active:true};
const t=(id,bu,date='2026-09-15',extra={})=>({...identity,id,ticketNumber:id,netBushels:bu,date,...extra});
const previous=[997.26,968.57,1005.36,976.07,983.93].map((bu,i)=>t('p'+i,bu,'2026-09-14',{haulingJobId:'old'}));
let result=buildAutomaticHaulingAssignment(t('450726',984.64),{haulingJobs:[old,next],tickets:previous});
assert.equal(result.sourceBushels,68.81);assert.equal(result.haulingJobSplitAllocations[0].bushels,915.83);
const split={...t('450726',984.64),haulingJobId:result.haulingJobId,haulingJobSplitAllocations:result.haulingJobSplitAllocations};
assert.equal(effectiveJobTotals([...previous,split]).get('old'),5000);
assert.equal(ticketJobBushels(split,'old'),68.81);assert.equal(ticketJobBushels(split,'next'),915.83);
assert.equal(buildAutomaticHaulingAssignment(t('new',982.71),{haulingJobs:[old,next],tickets:[...previous,split]}).haulingJobId,'next');
assert.equal(compatibleHaulingJob({...old,status:'closed',completed:false},t('n',100)),false);
for(const changed of [{buyerId:'other'},{deliveryLocationId:'other'},{customerId:'other'},{crop:'Soybeans'},{date:'2026-10-01'}])assert.equal(compatibleHaulingJob(next,t('n',100,'2026-09-15',changed)),false);
const spot={...t('449988',968.57),haulingJobId:'next',haulingJobSplitAllocations:[{sourceJobId:'next',haulingJobId:'',bushels:325.83,allocationType:'spot'}]};
assert.equal(ticketJobBushels(spot,'next'),642.74);assert.equal(ticketSpotBushels(spot,'next'),325.83);
assert.equal(ticketJobBushels({...spot,voided:true},'next'),0);
const broken={haulingJobs:[old,next],tickets:[...previous.map(x=>({...x,haulingJobId:null})),split,t('450984',941.43,'2026-09-16',{haulingJobId:'next'}),t('453298',982.71,'2026-09-23',{haulingJobId:'next'}),t('453353',976.33,'2026-09-23',{haulingJobId:'next'})]};
const preview=buildHaulingReconciliation(broken,old),totals=effectiveJobTotals(preview.state.tickets);
assert.equal(totals.get('old'),5000);assert.equal(totals.get('next'),2500);
assert.equal(buildHaulingReconciliation(preview.state,old).changes.length,0,'replay must be idempotent');
assert.equal(broken.tickets[0].haulingJobId,null,'preview must not mutate source');
for(const ticket of preview.state.tickets){const sum=[...effectiveJobTotals([ticket]).values()].reduce((a,b)=>a+b,0)+ticketSpotBushels(ticket,ticket.haulingJobId);assert.ok(Math.abs(sum-ticket.netBushels)<.005,'physical bushels conserved');}
const manual=t('manual',100,'2026-09-14',{manualHaulingOverride:true,haulingJobId:null,contractId:'untouched'});
const preserved=buildHaulingReconciliation({...broken,tickets:[...broken.tickets,manual]},old);
assert.equal(preserved.manualCount,1);assert.equal(preserved.state.tickets.find(x=>x.id==='manual'),manual);
for(const scenario of runGrainScenarios())assert.equal(scenario.pass,true,scenario.name);
console.log('PASS: rollover, completion flags, compatibility, Spot portions, voids, chronological repair, conservation, idempotency, manual protection, existing scenarios');

const {grainRecordSignature}=await import('../js/grain/operations/core/grain-integrity.js');
assert.equal(grainRecordSignature({id:'ticket',nested:{a:1,b:2},rows:[{a:1,b:2}]}),grainRecordSignature({rows:[{b:2,a:1}],nested:{b:2,a:1},id:'ticket'}));
assert.notEqual(grainRecordSignature({netBushels:100}),grainRecordSignature({netBushels:101}));
assert.notEqual(grainRecordSignature({splits:[1,2]}),grainRecordSignature({splits:[2,1]}));
console.log('PASS: Firestore record comparison ignores map order but detects value changes');

const extra=t('extra',960.36,'2026-09-23');
const overflowRepair=buildHaulingReconciliation({...preview.state,tickets:[...preview.state.tickets,extra]},old);
const repairedExtra=overflowRepair.state.tickets.find(t=>t.id==='extra');
assert.equal(ticketSpotBushels(repairedExtra,'next'),960.36);
assert.equal(effectiveJobTotals(overflowRepair.state.tickets).get('next'),2500);
assert.equal(buildHaulingReconciliation(overflowRepair.state,old).changes.length,0);
console.log('PASS: wholly unassigned historical overflow becomes Spot without exceeding capacity');
