// FarmVista Grain Operations — contract add/edit form model aligned to Firestore schema.
import { clean,number,round2 } from '../core/grain-rules.js';import { validateContract } from '../core/grain-validation.js';
const nullableNumber=v=>v===null||v===undefined||v===''?null:round2(number(v));
export function contractDraft(contract={}){return{id:clean(contract.id),buyerId:clean(contract.buyerId),buyerName:clean(contract.buyerName),deliveryLocationId:clean(contract.deliveryLocationId),deliveryLocationName:clean(contract.deliveryLocationName),deliveryStreet:clean(contract.deliveryStreet),deliveryCity:clean(contract.deliveryCity),deliveryState:clean(contract.deliveryState),deliveryZip:clean(contract.deliveryZip),crop:clean(contract.crop??contract.commodity),customerId:clean(contract.customerId??contract.grainCustomerId),grainCustomerId:clean(contract.grainCustomerId??contract.customerId),customerName:clean(contract.customerName??contract.soldUnder),contractNumber:clean(contract.contractNumber??contract.number),contractType:clean(contract.contractType??contract.type)||'Cash',contractDate:clean(contract.contractDate),bushels:round2(contract.contractBushels??contract.bushels??contract.quantity),deliveredBushels:nullableNumber(contract.deliveredBushels),openBushels:nullableNumber(contract.openBushels),futuresPrice:nullableNumber(contract.futuresPrice),basisPrice:nullableNumber(contract.basisPrice??contract.basis),cashPrice:nullableNumber(contract.pricePerBushel??contract.cashPrice??contract.price),deliveryStartDate:clean(contract.deliveryStart??contract.deliveryStartDate??contract.startDate),deliveryEndDate:clean(contract.deliveryEnd??contract.deliveryEndDate??contract.expirationDate??contract.endDate),status:clean(contract.status??contract.contractStatus)||'Open',notes:clean(contract.notes),spotLoadOnly:contract.spotLoadOnly===true}}
export function contractPayload(draft,{includeDerivedTotals=true}={}){const data=contractDraft(draft),bushels=Math.max(0,round2(data.bushels)),type=data.contractType;let futuresPrice=data.futuresPrice,basisPrice=data.basisPrice,pricePerBushel=data.cashPrice;if(type==='Basis'){futuresPrice=null;pricePerBushel=null}else if(type==='Futures'){basisPrice=null;pricePerBushel=null}else if(type==='Program'){futuresPrice=null;basisPrice=null}else if(type==='Cash'){pricePerBushel=futuresPrice!==null&&basisPrice!==null?round2(futuresPrice+basisPrice):pricePerBushel}const payload={buyerId:data.buyerId,buyerName:data.buyerName,customerId:data.customerId,customerName:data.customerName,crop:data.crop,contractType:type,contractNumber:data.contractNumber,contractDate:data.contractDate,contractBushels:bushels,spotLoadOnly:bushels===0,futuresPrice,basisPrice,pricePerBushel,deliveryLocationId:data.deliveryLocationId,deliveryLocationName:data.deliveryLocationName,deliveryStreet:data.deliveryStreet,deliveryCity:data.deliveryCity,deliveryState:data.deliveryState,deliveryZip:data.deliveryZip,deliveryStart:data.deliveryStartDate,deliveryEnd:data.deliveryEndDate,notes:data.notes,status:data.status};if(includeDerivedTotals){const delivered=data.deliveredBushels===null?0:data.deliveredBushels;payload.deliveredBushels=delivered;payload.openBushels=Math.max(0,round2(bushels-delivered))}return payload}
export function contractCreatePayload(draft){return contractPayload(draft,{includeDerivedTotals:true})}
// Editing contract terms must never rewrite delivery progress. Delivered/open bushels are read
// from the ticket allocation ledger, so leave both persisted counters untouched on edit.
export function contractEditPayload(draft){return contractPayload(draft,{includeDerivedTotals:false})}
export function validateContractDraft(draft){return validateContract({...contractPayload(draft,{includeDerivedTotals:false}),bushels:draft?.bushels??draft?.contractBushels})}
