// FarmVista Grain Operations — add/edit dialog rendering
import { getWorkspaceModel } from './workspace-controller.js';
import { haulingDraft, haulingPayload, validateHaulingDraft } from '../hauling/hauling-form.js';
import { contractDraft, contractPayload, validateContractDraft } from '../contracts/contract-form.js';
import { saveHaulingJob, saveContract } from '../data/grain-writes.js';
import { clean } from '../core/grain-rules.js';
const esc=v=>clean(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const id=()=>globalThis.crypto?.randomUUID?.()||`fv-${Date.now()}-${Math.random().toString(36).slice(2)}`;
const options=(items,value,label)=>items.map(x=>`<option value="${esc(x.id)}" ${clean(x.id)===clean(value)?'selected':''}>${esc(label(x))}</option>`).join('');
function field(label,name,value,type='text'){return `<label class="fv-go-field"><span>${label}</span><input name="${name}" type="${type}" value="${esc(value)}"></label>`}
function select(label,name,html){return `<label class="fv-go-field"><span>${label}</span><select name="${name}"><option value="">Select…</option>${html}</select></label>`}
function open(root,title,html){const modal=root.querySelector('#fv-go-detail-modal');modal.querySelector('.fv-go-modal-title').textContent=title;modal.querySelector('.fv-go-modal-body').innerHTML=html;modal.classList.add('open');return modal}
function commonChoices(model,draft){const buyers=model.locations.length?model.locations:model.buyers;return `${select('Destination','destinationId',options(buyers,draft.deliveryLocationId||draft.buyerId,x=>x.name||x.deliveryLocationName||x.buyerName||x.displayName||x.id))}${select('Crop','crop',`<option ${draft.crop==='Corn'?'selected':''}>Corn</option><option ${draft.crop==='Soybeans'?'selected':''}>Soybeans</option>`)}${select('Sold Under','customerId',options(model.customers,draft.customerId||draft.grainCustomerId,x=>x.name||x.customerName||x.displayName||x.id))}`}
function applyChoiceNames(form,draft,model){const destination=form.destinationId.value;const customer=form.customerId.value;const place=(model.locations.length?model.locations:model.buyers).find(x=>clean(x.id)===destination);const sold=model.customers.find(x=>clean(x.id)===customer);return{...draft,buyerId:destination,deliveryLocationId:destination,buyerName:clean(place?.buyerName??place?.name??place?.displayName),deliveryLocationName:clean(place?.deliveryLocationName??place?.name??place?.displayName),customerId:customer,grainCustomerId:customer,customerName:clean(sold?.customerName??sold?.name??sold?.displayName),crop:form.crop.value}}
export function openHaulingForm(root,job={}){const model=getWorkspaceModel(),draft=haulingDraft(job);const modal=open(root,draft.id?'Edit Hauling Job':'Add Hauling Job',`<form class="fv-go-form" data-go-form="hauling">${commonChoices(model,draft)}${field('Starting Bushels','startingBushels',draft.startingBushels||'','number')}${field('Delivery Start','deliveryStartDate',draft.deliveryStartDate,'date')}${field('Delivery End','deliveryEndDate',draft.deliveryEndDate,'date')}<label class="fv-go-field fv-go-field-wide"><span>Notes</span><textarea name="notes">${esc(draft.notes)}</textarea></label><div class="fv-go-form-errors" hidden></div><div class="fv-go-form-actions"><button type="button" class="fv-go-btn secondary fv-go-close-form">Cancel</button><button class="fv-go-btn" type="submit">Save Hauling Job</button></div></form>`);const form=modal.querySelector('form');form.addEventListener('submit',async e=>{e.preventDefault();let data=applyChoiceNames(form,{...draft,startingBushels:form.startingBushels.value,deliveryStartDate:form.deliveryStartDate.value,deliveryEndDate:form.deliveryEndDate.value,notes:form.notes.value},model);const errors=validateHaulingDraft(data),box=form.querySelector('.fv-go-form-errors');if(errors.length){box.hidden=false;box.textContent=errors.join(' • ');return}data=haulingPayload(data);try{await saveHaulingJob(data.id||id(),data);modal.classList.remove('open')}catch(error){box.hidden=false;box.textContent=error.message||'Save failed'}});modal.querySelector('.fv-go-close-form').onclick=()=>modal.classList.remove('open')}
export function openContractForm(root,contract={}){const model=getWorkspaceModel(),draft=contractDraft(contract);const modal=open(root,draft.id?'Edit Grain Contract':'Add Grain Contract',`<form class="fv-go-form" data-go-form="contract">${commonChoices(model,draft)}${field('Contract #','contractNumber',draft.contractNumber)}${select('Contract Type','contractType',['Cash','Basis','Futures','Program'].map(x=>`<option ${draft.contractType===x?'selected':''}>${x}</option>`).join(''))}${field('Bushels','bushels',draft.bushels||'','number')}<div class="fv-go-price-fields">${field('Futures','futuresPrice',draft.futuresPrice||'','number')}${field('Basis','basis',draft.basis||'','number')}${field('Cash','cashPrice',draft.cashPrice||'','number')}</div>${field('Delivery Start','deliveryStartDate',draft.deliveryStartDate,'date')}${field('Delivery End','deliveryEndDate',draft.deliveryEndDate,'date')}<label class="fv-go-field fv-go-field-wide"><span>Notes</span><textarea name="notes">${esc(draft.notes)}</textarea></label><div class="fv-go-form-errors" hidden></div><div class="fv-go-form-actions"><button type="button" class="fv-go-btn secondary fv-go-close-form">Cancel</button><button class="fv-go-btn" type="submit">Save Contract</button></div></form>`);const form=modal.querySelector('form');form.addEventListener('submit',async e=>{e.preventDefault();let data=applyChoiceNames(form,{...draft,contractNumber:form.contractNumber.value,contractType:form.contractType.value,bushels:form.bushels.value,futuresPrice:form.futuresPrice.value,basis:form.basis.value,cashPrice:form.cashPrice.value,deliveryStartDate:form.deliveryStartDate.value,deliveryEndDate:form.deliveryEndDate.value,notes:form.notes.value},model);const errors=validateContractDraft(data),box=form.querySelector('.fv-go-form-errors');if(errors.length){box.hidden=false;box.textContent=errors.join(' • ');return}data=contractPayload(data);try{await saveContract(data.id||id(),data);modal.classList.remove('open')}catch(error){box.hidden=false;box.textContent=error.message||'Save failed'}});modal.querySelector('.fv-go-close-form').onclick=()=>modal.classList.remove('open')}
